-- 迁移：为所有已启用 RLS 的业务表追加 FORCE ROW LEVEL SECURITY
-- 背景：PostgreSQL 中表 Owner 默认绕过 RLS 策略，必须显式 FORCE 才能让 Owner 也受约束。
--       SPEC §1.3 核心安全决策：RLS 必须数据库层强制、无法绕过。
-- 日期：2026-06-25

-- shared_* 基础表
ALTER TABLE shared_employees FORCE ROW LEVEL SECURITY;
ALTER TABLE shared_members FORCE ROW LEVEL SECURITY;
ALTER TABLE shared_products FORCE ROW LEVEL SECURITY;
ALTER TABLE shared_tables FORCE ROW LEVEL SECURITY;
ALTER TABLE shared_devices FORCE ROW LEVEL SECURITY;
ALTER TABLE shared_categories FORCE ROW LEVEL SECURITY;
ALTER TABLE shared_member_levels FORCE ROW LEVEL SECURITY;
ALTER TABLE shared_store_settings FORCE ROW LEVEL SECURITY;

-- pos_* 收银模块
ALTER TABLE pos_orders FORCE ROW LEVEL SECURITY;
ALTER TABLE pos_order_items FORCE ROW LEVEL SECURITY;
ALTER TABLE pos_payments FORCE ROW LEVEL SECURITY;
ALTER TABLE pos_refunds FORCE ROW LEVEL SECURITY;
ALTER TABLE pos_discount_approvals FORCE ROW LEVEL SECURITY;
ALTER TABLE pos_member_transactions FORCE ROW LEVEL SECURITY;
ALTER TABLE pos_desk_notes FORCE ROW LEVEL SECURITY;
ALTER TABLE pos_bookings FORCE ROW LEVEL SECURITY;
ALTER TABLE pos_payment_methods FORCE ROW LEVEL SECURITY;
ALTER TABLE pos_table_sessions FORCE ROW LEVEL SECURITY;
ALTER TABLE pos_order_logs FORCE ROW LEVEL SECURITY;
ALTER TABLE pos_daily_reconciliations FORCE ROW LEVEL SECURITY;

-- game_* 游戏模块
ALTER TABLE game_sessions FORCE ROW LEVEL SECURITY;

-- sys_* 系统表
ALTER TABLE sys_users FORCE ROW LEVEL SECURITY;
ALTER TABLE sys_notifications FORCE ROW LEVEL SECURITY;
ALTER TABLE sys_notification_settings FORCE ROW LEVEL SECURITY;
ALTER TABLE sys_printers FORCE ROW LEVEL SECURITY;
ALTER TABLE sys_print_routes FORCE ROW LEVEL SECURITY;
ALTER TABLE sys_print_queue FORCE ROW LEVEL SECURITY;

-- att_* 考勤模块
ALTER TABLE att_shift_configs FORCE ROW LEVEL SECURITY;
ALTER TABLE att_records FORCE ROW LEVEL SECURITY;
ALTER TABLE att_schedules FORCE ROW LEVEL SECURITY;
ALTER TABLE att_schedule_rules FORCE ROW LEVEL SECURITY;
ALTER TABLE att_schedule_snapshots FORCE ROW LEVEL SECURITY;
ALTER TABLE att_swap_requests FORCE ROW LEVEL SECURITY;
ALTER TABLE att_approvals FORCE ROW LEVEL SECURITY;
ALTER TABLE att_leave_balances FORCE ROW LEVEL SECURITY;

-- wage_* 工资模块
ALTER TABLE wage_periods FORCE ROW LEVEL SECURITY;
ALTER TABLE wage_salary_matrix FORCE ROW LEVEL SECURITY;
ALTER TABLE wage_contracts FORCE ROW LEVEL SECURITY;
ALTER TABLE wage_records FORCE ROW LEVEL SECURITY;
ALTER TABLE wage_record_items FORCE ROW LEVEL SECURITY;
ALTER TABLE wage_items_config FORCE ROW LEVEL SECURITY;
ALTER TABLE wage_salary_rules FORCE ROW LEVEL SECURITY;
ALTER TABLE wage_wework_payments FORCE ROW LEVEL SECURITY;
ALTER TABLE wage_disputes FORCE ROW LEVEL SECURITY;

-- hr_* 人力资源模块
ALTER TABLE hr_kpi_templates FORCE ROW LEVEL SECURITY;
ALTER TABLE hr_kpi_scores FORCE ROW LEVEL SECURITY;
ALTER TABLE hr_kpi_results FORCE ROW LEVEL SECURITY;
ALTER TABLE hr_kpi_appeals FORCE ROW LEVEL SECURITY;
ALTER TABLE hr_performance FORCE ROW LEVEL SECURITY;
ALTER TABLE hr_rankings FORCE ROW LEVEL SECURITY;
ALTER TABLE hr_guest_ratings FORCE ROW LEVEL SECURITY;
ALTER TABLE hr_penalty_notices FORCE ROW LEVEL SECURITY;

-- sig_* 签收模块
ALTER TABLE sig_tasks FORCE ROW LEVEL SECURITY;

-- butler_* 开闭店模块
ALTER TABLE butler_checklist_templates FORCE ROW LEVEL SECURITY;
ALTER TABLE butler_checklist_items FORCE ROW LEVEL SECURITY;
ALTER TABLE butler_sessions FORCE ROW LEVEL SECURITY;
ALTER TABLE butler_item_results FORCE ROW LEVEL SECURITY;

-- wine_* 存酒模块
ALTER TABLE wine_stored_bottles FORCE ROW LEVEL SECURITY;
ALTER TABLE wine_stocktakes FORCE ROW LEVEL SECURITY;
ALTER TABLE wine_stocktake_items FORCE ROW LEVEL SECURITY;

-- fin_* 财务模块
ALTER TABLE fin_daily_revenue FORCE ROW LEVEL SECURITY;
